version: "3.7"

services:  
  gogs:
    image: courselabs/gogs:0.12.3
    build:
      context: ./gogs

  jenkins:
    image: courselabs/jenkins:2.319.1
    build:
      context: ./jenkins

  sonarqube:
    image: courselabs/sonarqube:9.2.1
    build:
      context: ./sonarqube
  
  elasticsearch:
    image: courselabs/elasticsearch:7.10
    build: 
      context: ./elasticsearch
      args: 
        - ES_VERSION=7.10.2

  logstash:
    image: courselabs/logstash:7.10
    build: 
      context: ./logstash
      args: 
        - LOGSTASH_VERSION=7.10.2

  kibana:
    image: courselabs/kibana:7.10
    build: 
      context: ./kibana
      args: 
        - KIBANA_VERSION=7.10.2
        - NODE_TAG=10.23.1-alpine3.11
